version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

shared_environment: &shared_environment
  SHARED: banana
  DYNAMIC: `TZ="Europe/Moscow" date '+%Y%m%d%H%M'`

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
        environment:
          <<: *shared_environment
          SUBJECT: world
    executor: ruby/default
    steps:
      - run:
          name: Say hi
          command: |
            echo Hello ${SUBJECT}! Here is a ${SHARED}
            echo And a ${DYNAMIC}
