version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
        # environment:
        #   <<: *shared_environment
    executor: ruby/default
    steps:
      - run:
          command: |
            echo value: $(eval ${SHARED})
      - run:
          command: |
            git log --pretty='%ad' --date=format:'%Y-%m-%d-%H%M%S'
#   deploy:
#     docker:
#       - image: circleci/ruby:2.6.3-stretch-node
#         environment:
#           <<: *shared_environment
#     executor: ruby/default
#     steps:
#       - run:
#           command: |
#             echo value: $(eval $SHARED)

# shared_environment: &shared_environment
#   SHARED: "TZ='Europe/Moscow' date '+%Y%m%d%H%M'"
